In [2]:
import pandas as pd
import numpy as np

In [3]:
autos = pd.read_csv(r'C:\jupyter_notbook\jupyter_code_file\autos.csv')
print("file read successfully")

file read successfully

In [4]:
autos

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [5]:
autos.describe()

,index,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,nrOfPictures,postalCode
count,371528.000000,3.715280e+05,371528.000000,371528.000000,371528.000000,371528.000000,371528.0,371528.00000
mean,185763.500000,1.729514e+04,2004.577997,115.549477,125618.688228,5.734445,0.0,50820.66764
std,107251.039743,3.587954e+06,92.866598,192.139578,40112.337051,3.712412,0.0,25799.08247
min,0.000000,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,0.0,1067.00000
25%,92881.750000,1.150000e+03,1999.000000,70.000000,125000.000000,3.000000,0.0,30459.00000
50%,185763.500000,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,0.0,49610.00000
75%,278645.250000,7.200000e+03,2008.000000,150.000000,150000.000000,9.000000,0.0,71546.00000
max,371527.000000,2.147484e+09,9999.000000,20000.000000,150000.000000,12.000000,0.0,99998.00000

In [6]:
autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

In [7]:
autos['dateCrawled'] = pd.to_datetime(autos['dateCrawled'], format='%Y-%m-%d %H:%M:%S')
autos['datecreated'] = pd.to_datetime(autos['dateCreated'])
autos['lastSeen'] = pd.to_datetime(autos['lastSeen'], format='%Y-%m-%d %H:%M:%S')

print("dtype converted successfully")

dtype converted successfully

In [8]:
autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  datetime64[us]
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  datetime64[us]
 21  datecreated          371528 non-null  datetime64[us]
dtypes: datetime64[us](3), int64(8), str(11)
memory usage: 62.4 MB

In [9]:
autos.isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
datecreated                0
dtype: int64

In [10]:
autos['fuelType'] = autos['fuelType'].fillna(autos['fuelType'].mode()[0])

In [11]:
autos. isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType                   0
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
datecreated                0
dtype: int64

In [12]:
autos

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen,datecreated
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57,2016-03-24
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50,2016-03-24
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46,2016-03-14
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17,2016-03-17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21,2016-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,20000,1,benzin,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52,2016-03-14
371524,371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12,2016-03-05
371525,371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26,2016-03-19
371526,371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21,2016-03-20
371527,371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10,2016-03-07

In [13]:
autos['notRepairedDamage'] = autos['notRepairedDamage'].replace({
    'ja': 'yes', 
    'nein': 'no'
})

In [14]:

damage_counts = autos['notRepairedDamage'].value_counts(normalize=True)
print(damage_counts)

notRepairedDamage
no     0.878832
yes    0.121168
Name: proportion, dtype: float64

In [15]:
autos.drop('nrOfPictures', axis=1, inplace=True)

In [16]:
autos['notRepairedDamage'] = autos['notRepairedDamage'].fillna(autos['notRepairedDamage'].mode()[0])

In [17]:
autos

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,postalCode,lastSeen,datecreated
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,no,2016-03-24 00:00:00,70435,2016-04-07 03:16:57,2016-03-24
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,yes,2016-03-24 00:00:00,66954,2016-04-07 01:46:50,2016-03-24
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,no,2016-03-14 00:00:00,90480,2016-04-05 12:47:46,2016-03-14
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,no,2016-03-17 00:00:00,91074,2016-03-17 17:40:17,2016-03-17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,no,2016-03-31 00:00:00,60437,2016-04-06 10:17:21,2016-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,benzin,sonstige_autos,no,2016-03-14 00:00:00,39576,2016-04-06 00:46:52,2016-03-14
371524,371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,no,2016-03-05 00:00:00,26135,2016-03-11 18:17:12,2016-03-05
371525,371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,no,2016-03-19 00:00:00,87439,2016-04-07 07:15:26,2016-03-19
371526,371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,no,2016-03-20 00:00:00,40764,2016-03-24 12:45:21,2016-03-20
371527,371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,no,2016-03-07 00:00:00,73326,2016-03-22 03:17:10,2016-03-07

In [18]:
autos.dropna(subset=['vehicleType'], inplace=True)
autos.dropna(subset=['gearbox'], inplace=True)
autos.dropna(subset=['model'], inplace=True)

In [19]:
autos.isnull().sum()

index                  0
dateCrawled            0
name                   0
seller                 0
offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
postalCode             0
lastSeen               0
datecreated            0
dtype: int64

In [20]:
autos.isnull().sum()

index                  0
dateCrawled            0
name                   0
seller                 0
offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
postalCode             0
lastSeen               0
datecreated            0
dtype: int64

In [21]:
autos['vehicle_age'] =2026 - autos['yearOfRegistration']
print(autos[["name", "yearOfRegistration", "vehicle_age", "price"]].head())

                                                name  yearOfRegistration  \
2                     Jeep_Grand_Cherokee_"Overland"                2004
3                                 GOLF_4_1_4__3TÜRER                2001
4                     Skoda_Fabia_1.4_TDI_PD_Classic                2008
5  BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...                1995
6                        Peugeot_206_CC_110_Platinum                2004

   vehicle_age  price
2           22   9800
3           25   1500
4           18   3600
5           31    650
6           22   2200

In [22]:

autos.to_csv('cleaned_autos1.csv', index=False)
print("File successfully updated and saved as cleaned_autos1.csv")

File successfully updated and saved as cleaned_autos1.csv

In [23]:
autos[['brand', 'gearbox', 'model', 'fuelType', 'kilometer']].head()

        brand    gearbox    model fuelType  kilometer
2        jeep  automatik    grand   diesel     125000
3  volkswagen    manuell     golf   benzin     150000
4       skoda    manuell    fabia   diesel      90000
5         bmw    manuell      3er   benzin     150000
6     peugeot    manuell  2_reihe   benzin     150000

In [24]:
autos.describe()

,index,dateCrawled,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,postalCode,lastSeen,datecreated,vehicle_age
count,311149.000000,311149,3.111490e+05,311149.000000,311149.000000,311149.000000,311149.000000,311149.000000,311149,311149,311149.000000
mean,185697.223465,2016-03-21 14:02:13.630322,9.385967e+03,2002.820983,122.868870,125609.868584,6.015922,51308.935115,2016-03-30 08:22:14.172297,2016-03-20 20:12:21.175449,23.179017
min,2.000000,2016-03-05 14:06:22,0.000000e+00,1910.000000,0.000000,5000.000000,0.000000,1067.000000,2016-03-05 14:15:08,2015-03-20 00:00:00,8.000000
25%,92773.000000,2016-03-13 13:06:34,1.350000e+03,1999.000000,75.000000,100000.000000,3.000000,30926.000000,2016-03-23 18:30:49,2016-03-13 00:00:00,19.000000
50%,185648.000000,2016-03-21 18:49:04,3.390000e+03,2003.000000,113.000000,150000.000000,6.000000,50354.000000,2016-04-04 11:56:24,2016-03-21 00:00:00,23.000000
75%,278573.000000,2016-03-29 15:44:41,7.900000e+03,2007.000000,150.000000,150000.000000,9.000000,72218.000000,2016-04-06 11:17:32,2016-03-29 00:00:00,27.000000
max,371527.000000,2016-04-07 14:36:58,1.000000e+08,2018.000000,20000.000000,150000.000000,12.000000,99998.000000,2016-04-07 14:58:51,2016-04-07 00:00:00,116.000000
std,107269.383294,NaN,5.168193e+05,6.592346,182.252782,39245.087970,3.573453,25797.841722,NaN,NaN,6.592346

In [30]:
autos["fuelType"] = autos["fuelType"].fillna(autos["fuelType"].mode()[0])
autos["notRepairedDamage"] = autos["notRepairedDamage"].fillna(
    autos["notRepairedDamage"].mode()[0]
)

autos.dropna(subset=["vehicleType", "gearbox", "model"], inplace=True)

autos.isna().sum()

index                  0
dateCrawled            0
name                   0
seller                 0
offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
postalCode             0
lastSeen               0
datecreated            0
vehicle_age            0
dtype: int64

In [31]:
autos.describe()

,index,dateCrawled,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,postalCode,lastSeen,datecreated,vehicle_age
count,311149.000000,311149,3.111490e+05,311149.000000,311149.000000,311149.000000,311149.000000,311149.000000,311149,311149,311149.000000
mean,185697.223465,2016-03-21 14:02:13.630322,9.385967e+03,2002.820983,122.868870,125609.868584,6.015922,51308.935115,2016-03-30 08:22:14.172297,2016-03-20 20:12:21.175449,23.179017
min,2.000000,2016-03-05 14:06:22,0.000000e+00,1910.000000,0.000000,5000.000000,0.000000,1067.000000,2016-03-05 14:15:08,2015-03-20 00:00:00,8.000000
25%,92773.000000,2016-03-13 13:06:34,1.350000e+03,1999.000000,75.000000,100000.000000,3.000000,30926.000000,2016-03-23 18:30:49,2016-03-13 00:00:00,19.000000
50%,185648.000000,2016-03-21 18:49:04,3.390000e+03,2003.000000,113.000000,150000.000000,6.000000,50354.000000,2016-04-04 11:56:24,2016-03-21 00:00:00,23.000000
75%,278573.000000,2016-03-29 15:44:41,7.900000e+03,2007.000000,150.000000,150000.000000,9.000000,72218.000000,2016-04-06 11:17:32,2016-03-29 00:00:00,27.000000
max,371527.000000,2016-04-07 14:36:58,1.000000e+08,2018.000000,20000.000000,150000.000000,12.000000,99998.000000,2016-04-07 14:58:51,2016-04-07 00:00:00,116.000000
std,107269.383294,NaN,5.168193e+05,6.592346,182.252782,39245.087970,3.573453,25797.841722,NaN,NaN,6.592346

In [29]:
autos.isna().sum()

index                  0
dateCrawled            0
name                   0
seller                 0
offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
postalCode             0
lastSeen               0
datecreated            0
vehicle_age            0
dtype: int64